# Generated by Django 3.2.5 on 2021-07-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Phonenumber', models.CharField(max_length=255)),
                ('Language', models.CharField(max_length=255)),
                ('Currency', models.CharField(max_length=255)),
            ],
        ),
    ]
