# Generated by Django 3.2.5 on 2021-07-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moztest', '0003_alter_area_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='provider',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
