# Generated by Django 3.2.5 on 2021-07-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moztest', '0005_alter_area_coords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='coords',
            field=models.TextField(),
        ),
    ]
